
(require 'android-defs)
(require 'srfi-1)

(define-alias gl10 javax.microedition.khronos.opengles.GL10)
(define-alias egl-config javax.microedition.khronos.egl.EGLConfig)
(define-alias renderer android.opengl.GLSurfaceView$Renderer)
(define-alias glu android.opengl.GLU)

(define-simple-class lesson05 (renderer)
  ;; an all-purpose state variable
  (mys::gnu.lists.Pair access: 'private init: '(0 0 0 0))
  ;; I was getting ClassCastException, so I set them to Object.
  (pyramid :: Object)
  (pyramid2 :: Object)
  (cube :: Object)
  (cube2 :: Object)
  ((*init*)
   (set! pyramid (Pyramid))
   (set! pyramid2 (Pyramid))
   (set! cube (Cube))
   (set! cube2 (Cube)))
  ((onSurfaceCreated (gl :: gl10) (config :: egl-config)) :: void
   (gl:glShadeModel gl10:GL_SMOOTH)
   (gl:glClearColor 0.0 0.0 0.0 0.5)
   (gl:glClearDepthf 1.0)
   (gl:glEnable gl10:GL_DEPTH_TEST)
   (gl:glDepthFunc gl10:GL_LEQUAL)
   (gl:glHint gl10:GL_PERSPECTIVE_CORRECTION_HINT gl10:GL_NICEST))
  ((onDrawFrame (gl :: gl10)) :: void
   (gl:glClear (bitwise-ior gl10:GL_COLOR_BUFFER_BIT gl10:GL_DEPTH_BUFFER_BIT))
   (gl:glLoadIdentity)
   (gl:glTranslatef 0.8 -1.0 -7.0)
   (gl:glScalef 0.5 0.5 0.5)
   (gl:glRotatef (first mys) 0.0 1.0 1.0)
   (cube:draw gl)
   (gl:glLoadIdentity)
   (gl:glTranslatef -0.8 1.0 -7.0)
   (gl:glScalef 0.5 0.5 0.5)
   (gl:glRotatef (second mys) 1.0 0.0 1.0)
   (cube2:draw gl)
   (gl:glLoadIdentity)
   (gl:glTranslatef 0.8 1.0 -6.0)
   (gl:glScalef 0.5 0.5 0.5)
   (gl:glRotatef (third mys) 0.3 1.0 0.0)
   (pyramid:draw gl)
   (gl:glLoadIdentity)
   (gl:glTranslatef -0.8 -1.0 -6.0)
   (gl:glScalef 0.5 0.5 0.5)
   (gl:glRotatef (fourth mys) 0.0 0.9 0.3)
   (pyramid2:draw gl))
  ((onSurfaceChanged (gl :: gl10) (width :: int) (height :: int)) :: void
   (set! height (if (= height 0) 1 height))
   (gl:glViewport 0 0 width height)
   (gl:glMatrixMode gl10:GL_PROJECTION)
   (gl:glLoadIdentity)
   (glu:gluPerspective gl 45 (/ (as float width) (as float height)) 0.1 100.0)
   (gl:glMatrixMode gl10:GL_MODELVIEW)
   (gl:glLoadIdentity))
  ((setState (news::gnu.lists.Pair))::void
   (set! mys news))
  ((getState)::gnu.lists.Pair
   mys)
)
